# -*- coding: utf-8 -*-
"""Amazon_Prime_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptPSMlimLY157KiRF4ak8248cC2r8ug8

# project_name  

**"Amazon Prime Analysis"**

project_type = "EDA"

contribution = "Individual"

# project_summary

**"This project explores the dataset of Amazon Prime Video to analyze the distribution of genres, production countries, trends over time, and IMDb/TMDB ratings. The goal is to extract insights regarding content diversity, production sources, and audience ratings."**

# github_link =

"<Add your GitHub link here>"

# Problem Statement

This dataset was created to analyze all shows available on Amazon Prime Video, allowing us to extract valuable insights such as:

- Content Diversity: What genres and categories dominate the platform?

- Regional Availability: How does content distribution vary across different regions?

- Trends Over Time: How has Amazon Prime's content library evolved?

- IMDb Ratings & Popularity: What are the highest-rated or most popular shows on the platform?

By analyzing this dataset, businesses, content creators, and data analysts can uncover key trends that influence subscription growth, user engagement, and content investment strategies in the streaming industry.

# Business Objective

The objective of this project is to analyze Amazon Prime Video's content catalog to extract insights about genre distribution, production origins, release trends, and audience ratings. By conducting Exploratory Data Analysis (EDA), we aim to answer key business questions such as:

- What genres dominate Amazon Prime Video?

- Which countries contribute the most content?

- How has content production evolved over the years?

- What is the overall audience perception based on IMDb and TMDB ratings?

These insights can help content strategists, marketers, and decision-makers understand trends in streaming content and make data-driven decisions for acquisitions, recommendations, and platform growth strategies.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

titles_df = pd.read_csv("titles.csv")

credits_df = pd.read_csv("credits.csv")

titles_df.head()

credits_df.head()

# Display basic info about datasets
print("Titles Dataset:")
print(titles_df.info())
print("\nCredits Dataset:")
print(credits_df.info())

# Check for missing values
def missing_values(df):
    return df.isnull().sum().sort_values(ascending=False)

print("\nMissing Values in Titles:")
print(missing_values(titles_df))
print("\nMissing Values in Credits:")
print(missing_values(credits_df))

# Drop unnecessary columns if required (e.g., imdb_id if not used)
titles_df.drop(columns=['imdb_id'], inplace=True)

# Convert release_year to numeric and filter valid years
titles_df['release_year'] = pd.to_numeric(titles_df['release_year'], errors='coerce')
titles_df = titles_df[titles_df['release_year'] > 1900]  # Keep only valid years

# Set visualization style
sns.set(style="darkgrid")

# Ensure genres are properly split into individual categories
titles_df['genres'] = titles_df['genres'].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Flatten genre list and count occurrences
genre_counts = pd.Series([genre for sublist in titles_df['genres'] for genre in sublist]).value_counts()

# Limit to top 20 genres for readability
top_genres = genre_counts.head(20)

# Plot
plt.figure(figsize=(12, 6))
sns.barplot(x=top_genres.index, y=top_genres.values, palette="viridis")
plt.xticks(rotation=45, ha='right')
plt.xlabel("Genres")
plt.ylabel("Count")
plt.title("Top 20 Genres on Amazon Prime Video")

# Annotate bars with counts
for index, value in enumerate(top_genres.values):
    plt.text(index, value + 5, str(value), ha='center', fontsize=10)

plt.show()

"""**Genre Distribution Insights:**

- Drama is the most common genre, followed by Comedy and Thriller.

- Reality, Sport, and War genres are the least represented.
"""

# Production Country Distribution
titles_df['production_countries'] = titles_df['production_countries'].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Flatten production countries list and count occurrences
country_counts = pd.Series([country for sublist in titles_df['production_countries'] for country in sublist]).value_counts().head(10)

# Production Country Distribution
plt.figure(figsize=(12, 6))
sns.barplot(x=country_counts.index, y=country_counts.values, palette="mako")
plt.xticks(rotation=45, ha='right')
plt.xlabel("Production Countries")
plt.ylabel("Count")
plt.title("Top 10 Production Countries on Amazon Prime Video")

# Annotate bars with counts
for index, value in enumerate(country_counts.values):
    plt.text(index, value + 5, str(value), ha='center', fontsize=10)

plt.show()

"""**Production Country Insights:**

- The U.S. dominates content production on Amazon Prime Video, far ahead of other countries.

- India and the U.K. are the next biggest contributors.

- Other major content-producing countries include Canada, France, Japan, and Germany.
"""

# Visualization: Content Production Over Time
plt.figure(figsize=(12, 6))
sns.histplot(titles_df['release_year'], bins=30, kde=True, color='blue')
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")
plt.title("Number of Titles Released Over Time")
plt.show()

"""**Content Release Trends:**

- There is a sharp increase in content releases after 2010, aligning with the rise of streaming services.

- The peak occurs around 2019-2021, indicating aggressive content expansion.

- 2024 shows a sudden drop, likely due to incomplete data.
"""

# IMDb and TMDB Score Distribution
plt.figure(figsize=(12, 6))
sns.histplot(titles_df['imdb_score'], bins=20, kde=True, color="blue", label="IMDb Score")
sns.histplot(titles_df['tmdb_score'], bins=20, kde=True, color="red", label="TMDB Score", alpha=0.6)
plt.xlabel("Score")
plt.ylabel("Count")
plt.title("Distribution of IMDb and TMDB Scores on Amazon Prime Video")
plt.legend()
plt.show()

"""**IMDb & TMDB Rating Insights:**

- Most content has scores between 5 and 7, meaning the majority of titles are rated average.

- There are very few extremely high (9+) or low-rated (below 3) titles.

- TMDB scores are slightly higher on average than IMDb scores, which could indicate different rating biases.
"""



# Top 10 Most Frequently Appearing Actors
actor_counts = Counter([actor for sublist in credits_df[credits_df['role'] == 'ACTOR']['name'] for actor in str(sublist).split(', ')])
top_actors = actor_counts.most_common(10)
top_actors_df = pd.DataFrame(top_actors, columns=['Actor', 'Appearance Count'])

plt.figure(figsize=(12, 6))
sns.barplot(y=top_actors_df['Actor'], x=top_actors_df['Appearance Count'], palette="coolwarm")
plt.xlabel("Number of Appearances")
plt.ylabel("Actor")
plt.title("Top 10 Most Frequently Appearing Actors on Amazon Prime Video")
plt.show()

"""**Top 10 Most Frequently Appearing Actors**

- George 'Gabby' Hayes is the most featured actor with 49 appearances.

- Roy Rogers, Bess Flowers, and Gene Autry also have high representation.

 The list contains actors from classic and Western films, indicating a large catalog of older titles.
"""

# Top 10 Most Frequently Directing Directors
director_counts = Counter([director for sublist in credits_df[credits_df['role'] == 'DIRECTOR']['name'] for director in str(sublist).split(', ')])
top_directors = director_counts.most_common(10)
top_directors_df = pd.DataFrame(top_directors, columns=['Director', 'Directed Titles'])

plt.figure(figsize=(12, 6))
sns.barplot(y=top_directors_df['Director'], x=top_directors_df['Directed Titles'], palette="magma")
plt.xlabel("Number of Titles Directed")
plt.ylabel("Director")
plt.title("Top 10 Most Frequently Directing Directors on Amazon Prime Video")
plt.show()

""" **Top 10 Most Frequently Directing Directors**

- Joseph Kane leads with 41 directed titles.

- Sam Newfield and Jay Chapman also directed many titles.

These directors were highly active in classic Western and action films, suggesting Amazon Prime Video's catalog has a significant number of old-school films.
"""

# Top 10 Content Producing Countries
country_counts = Counter([country for sublist in titles_df['production_countries'].dropna().astype(str) for country in sublist.split(', ')])
top_countries = country_counts.most_common(10)
top_countries_df = pd.DataFrame(top_countries, columns=['Country', 'Number of Titles'])

plt.figure(figsize=(12, 6))
sns.barplot(y=top_countries_df['Country'], x=top_countries_df['Number of Titles'], palette="viridis")
plt.xlabel("Number of Titles Produced")
plt.ylabel("Country")
plt.title("Top 10 Countries Producing Content on Amazon Prime Video")
plt.show()

"""**Top 10 Content-Producing Countries on Amazon Prime Video**

- The U.S. dominates with 4,809 titles, far ahead of other regions.

- India (1,048 titles) and the UK (667 titles) also contribute significantly.

Unclassified entries (~821 titles) indicate missing metadata, requiring cleanup
"""

# Genre Trends Over Time
genre_years = titles_df.explode('genres').groupby(['release_year', 'genres']).size().unstack().fillna(0)
top_genres = genre_years.sum().sort_values(ascending=False).head(6).index

plt.figure(figsize=(14, 7))
for genre in top_genres:
    sns.lineplot(x=genre_years.index, y=genre_years[genre], label=genre)

plt.xlabel("Release Year")
plt.ylabel("Number of Titles")
plt.title("Trends of Top Genres Over Time on Amazon Prime Video")
plt.legend(title="Genres")
plt.show()

"""**Genre Trends Over Time on Amazon Prime Video**

- Drama is the most dominant genre, with a sharp increase post-2000.

- Comedy, Thriller, and Action genres have also seen a significant rise in recent years.

- Crime and Romance have shown a steady increase but at a lower rate.

- A spike in content production after 2010 indicates Amazon Prime Video’s aggressive expansion.
"""

# IMDb Rating Distribution for Movies vs. TV Shows
print(titles_df.columns)

movies = titles_df[titles_df['type'] == 'MOVIE']
tv_shows = titles_df[titles_df['type'] == 'SHOW']

plt.figure(figsize=(12, 6))
sns.kdeplot(movies['imdb_score'].dropna(), label="Movies", shade=True, color='blue')
sns.kdeplot(tv_shows['imdb_score'].dropna(), label="TV Shows", shade=True, color='red')
plt.xlabel("IMDb Score")
plt.ylabel("Density")
plt.title("IMDb Rating Distribution: Movies vs. TV Shows")
plt.legend()
plt.show()

"""**TV shows on Amazon Prime generally have higher IMDb scores compared to movies, which show a wider spread of ratings.**

# Solution to Business Objective:

**To address our business objectives, we conducted Exploratory Data Analysis (EDA) on Amazon Prime Video’s dataset. Below are our key findings and how they help in decision-making:**

1. Genre Distribution Analysis:
Identified the most and least popular genres on the platform.
Insight: Helps Amazon optimize content acquisition and recommendations based on genre preferences.

2. Production Country Analysis:
Analyzed the top 10 content-producing countries.
Insight: Understanding regional content trends allows Amazon to target country-specific content strategies.

3. Trends Over Time:
Visualized how content production has evolved over different years.
Insight: Aids in predicting future content production trends and ensuring a balanced catalog of classic and recent titles.

4. IMDb & TMDB Rating Distribution:
Compared rating distributions to understand content quality.
Insight: Amazon can focus on promoting highly-rated content while re-evaluating low-rated ones.

# Conclusion:

Through this analysis of Amazon Prime Video, we have uncovered several key insights:

**Genre Distribution**

- Some genres are significantly more common than others, indicating content preferences.

-This insight can help Amazon optimize content recommendations and acquisition strategies.

**Production Country Analysis**

- The majority of content originates from a few dominant countries, mainly the USA, India, and the UK.

- This emphasizes regional content trends and highlights potential areas for expansion.

**Trends Over Time**

- The number of content releases has generally increased over time, reflecting the rapid growth of streaming platforms.
- Amazon can use this trend to predict future demand and ensure a balanced content library.

IMDb & TMDB Ratings Distribution

- Most titles have ratings between 5 and 8, indicating an average audience perception.
- Understanding these ratings helps Amazon focus on promoting highly-rated content while reconsidering underperforming titles.


**This exploratory data analysis provides valuable insights into Amazon Prime Video's content distribution, helping shape business decisions regarding content acquisition, marketing strategies, and user engagement improvements.**
"""



